"""Fix created_at timezone

Revision ID: f768100595e5
Revises: 0b8b344360cc
Create Date: 2025-05-15 15:34:42.642651

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f768100595e5"
down_revision = "0b8b344360cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###
